# Generated by Django 3.1.5 on 2021-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('ISO3', models.CharField(max_length=3, unique=True)),
                ('ISO2', models.CharField(max_length=2)),
                ('population', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['Country'],
            },
        ),
        migrations.CreateModel(
            name='CovidDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=10)),
                ('Country', models.CharField(max_length=100)),
                ('Confirmed', models.IntegerField(default=0)),
                ('Recovered', models.IntegerField(default=0)),
                ('Deaths', models.IntegerField(default=0)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('Population', models.IntegerField(default=0)),
                ('Daily_tests', models.IntegerField(default=0)),
                ('Daily_recovered', models.IntegerField(default=0)),
                ('Daily_deaths', models.IntegerField(default=0)),
                ('Daily_cases', models.IntegerField(default=0)),
                ('Active_cases', models.IntegerField(default=0)),
                ('Active_per_100k', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Daily_cases_smooth', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Daily_deaths_smooth', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Positive_test_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Tests_per_case', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Case_fatality', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Incidence_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('p_scores_all_ages', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('p_scores_15_64', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('p_scores_65_74', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('p_scores_75_84', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('p_scores_85plus', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('deaths_2020_all_ages', models.IntegerField(default=0)),
                ('average_deaths_2015_2019_all_ages', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('deaths_2015_all_ages', models.IntegerField(default=0)),
                ('deaths_2016_all_ages', models.IntegerField(default=0)),
                ('deaths_2017_all_ages', models.IntegerField(default=0)),
                ('deaths_2018_all_ages', models.IntegerField(default=0)),
                ('deaths_2019_all_ages', models.IntegerField(default=0)),
                ('deaths_2010_all_ages', models.IntegerField(default=0)),
                ('deaths_2011_all_ages', models.IntegerField(default=0)),
                ('deaths_2012_all_ages', models.IntegerField(default=0)),
                ('deaths_2013_all_ages', models.IntegerField(default=0)),
                ('deaths_2014_all_ages', models.IntegerField(default=0)),
                ('Week', models.IntegerField(default=0)),
                ('deaths_2021_all_ages', models.IntegerField(default=0)),
            ],
        ),
    ]
