# Generated by Django 3.1.5 on 2021-01-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('population', models.IntegerField(default=0)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.continent')),
            ],
        ),
        migrations.CreateModel(
            name='CovidCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('dailyCases', models.IntegerField(default=0)),
                ('dailyRecovered', models.IntegerField(default=0)),
                ('dailyDeaths', models.IntegerField(default=0)),
                ('activeCases', models.IntegerField(default=0)),
                ('activeCasesPer100k', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dailyCasesSmooth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dailyRecoveredSmooth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dailyDeathsSmooth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mortality', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caseFatality', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('incidenceRate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.country')),
            ],
        ),
        migrations.CreateModel(
            name='CovidApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('confirmed', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.country')),
            ],
        ),
    ]
